version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "deploy-custom-resource-flow-app"
s3_bucket = "<bucket>"
s3_prefix = "customresourceapp"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"